### ISSUE TITLE
How to decouple the pose and expression

### ISSUE THREAD

**Issue by endlessll** [gafniguy/4D-Facial-Avatars#5]
Hi:
Thank you for your wonderful work !
we are trying to re-implement your work with the dateset you provided,  the model seems fit the trainning set well, but some of the     images in test set cannot be predicted correctly and the predicted images get worse when changing the pose or expression. It seems that the pose and expression are not decoupled with out model.
Is there any network design or trainning tricks we should notice ?

Thank you very much.

**Comment by gafniguy** [comment]
Hey, 

thanks! 

I noticed sometimes that the model is able to pick up some correlation between an expression vector and a head pose it came with. When having an extreme difference between the original captured pose and the one you are manually choosing to render with. I believe this arises from the face tracker that has some bias. We tried some things in the past to decorrelate them (e.g. ideas from Fader Networks (Lample et al), but not successfully. For the sake of an experiment, you can try training the network without viewdir conditioning and see if it helps. 

However, if you run test data, where expression vectors were together with their tracked poses, it should always be fine. The same goes for cross subject re-enactment. With cross-subject I think there is a little bit less correlation pose-expression correlation.

**Comment by endlessll** [comment]
Thanks very much for your reply and advice !

I tried trainning the network without viewdir conditions, but it didn't get better enough to reach the effect of your demo in the paper. There are still some wrong gernerated images using the pose and expression in test set. 
I think there is somthing wrong in our implement. In your paper "The last sample on the ray r is assumed to lie on the background with a fixed color," how do you deal with the output σ of the last sample if fixing the output of color, we just simply give a fixed value of sigma_s or alpha for the last sample in the code. Is that proper for the network?

**Comment by gafniguy** [comment]
I actually still use the predicted density of that point. The network chooses to "use" our artificial background by just putting very low densities on all the points leading to that one. Try not fixing that density. Also, make sure to exclude the colour of the background from any sigmoid that happens on the predicted RGB's later. 

Also, note that I changed the nerf code to support different intrinsics fx,fy,cx,cy. In the nerf implementations it's typically fx==fy, cx=cy=0.5.

**Comment by gafniguy** [comment]
PS You can maybe share some results here, I might have some insights

**Comment by endlessll** [comment]
Thank you very much！ 
It works, the generated images in test set are all normal and clearer than before. I want to ask why one of fx and fy is positive and the other is negtive in your setting, should we calibrate the camera and get intrinsic parameters first if we use our own data. Do we need to pre-process the intrinsic parameters?
Thanks again for your help !

**Comment by endlessll** [comment]
![image](https://user-images.githubusercontent.com/40845486/120742528-9e979f80-c529-11eb-93cb-fb7415db78a7.png)
The result get much better now

**Comment by gafniguy** [comment]
Yeah that looks good! Glad it worked for you.

The minus in fy comes from the face tracker we used (face2face, Thies et al.)

**Comment by anthonyyuan** [comment]
hi ,can u give install resume and  docker?

**Comment by Tara8573** [comment]
Hi! Thank you for your wonderful work! Where could  we find the code of the face tracker (face2face, Thies et al.) you mentioned above?

**Comment by gafniguy** [comment]
> hi ,can u give install resume and docker?

I plan to give instructions but not a Docker, sorry!

**Comment by gafniguy** [comment]
> Hi! Thank you for your wonderful work! Where could we find the code of the face tracker (face2face, Thies et al.) you mentioned above?

Unfortunately, I do not own that code so can't publish it... If you need it to run a comparison for a paper, shoot me and Justus an email and we'll see what can be done :)

**Comment by Tara8573** [comment]
Hi! Thank you for your reply!&nbsp;
To compare with your wonderful model, I tried to train your model with my own data, but I couldn’t generate the corresponding parameters as those in transforms_train.json currently.
I would appreciate it if you could send the code for generating the parameters in&nbsp;transforms_train.json&nbsp;to me.
Thank you so much!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gafniguy/4D-Facial-Avatars"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月1日(星期五) 凌晨0:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gafniguy/4D-Facial-Avatars] How to decouple the pose and expression (#5)





  
Hi! Thank you for your wonderful work! Where could we find the code of the face tracker (face2face, Thies et al.) you mentioned above?
  
Unfortunately, I do not own that code so can't publish it... If you need it to run a comparison for a paper, shoot me and Justus an email and we'll see what can be done :)
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
